spring:
  datasource:
    url: jdbc:postgresql://db:5432/jobmanager_test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
liquibase:
  changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
  driver: org.postgresql.Driver
  url: jdbc:postgresql://db:5432/jobmanager_test
  username: postgres
  password: postgres