spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
liquibase:
  changeLogFile: classpath:db/changelog/db.changelog-master.yaml
  databaseChangelogTableName: jobmanager_DATABASECHANGELOG
  databaseChangelogLockTableName: jobmanager_DATABASECHANGELOGLOCK
  driver: org.postgresql.Driver
  url: jdbc:postgresql://db:5432/postgres
  username: postgres
  password: postgres